name: 'Terraform Infra Plan'

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

env:
    AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
    AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
    AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
     - name: Checkout
       uses: actions/checkout@v3

     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        audience: sts.amazonaws.com

     # Install the latest version of Terraform CLI and configure the Terraform CLI configuration.
     - name: Install Terraform
       uses: hashicorp/setup-terraform@v2

     - name: Configure Auth0 Credentials
       run: |
          export "TF_VAR_AUTH0_DOMAIN=$AUTH0_DOMAIN"
          export "TF_VAR_AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID"
          export "TF_VAR_AUTH0_CLIENT_SECRET=$AUTH0_CLIENT_SECRET"

     # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
     - name: Terraform Init
       run: |
        echo "** Running Terraform Init **"
        terraform init

     # Generates an execution plan for Terraform
     - name: Terraform Plan
       run: |
        echo "** Running Terraform Plan **"
        terraform plan